baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'The Illustrated NetHack Monsters'
#theme = 'ananke'
theme = 'risotto'
sectionPagesMenu = 'main'

[markup.goldmark.renderer]
unsafe= true
